set REPO_DRIVE=D:
set TOWERFALL_DRIVE=C:

set BUILD_NAME=TFModFortRiseTournament
set DLL_MOD_FILE_NAME=TFModFortRiseTournament.dll
set PDB_MOD_FILE_NAME=TFModFortRiseTournament.pdb
set MODULE_DIR_NAME=Ebe1.Tournament

set REPO_PATH=D:\__dev\code\tf-mod-fortrise-tournament\
set REPO_SCRIPT_PATH=%REPO_PATH%script\
set REPO_BUILD_PATH=%REPO_PATH%VSCode\bin\Debug\net10.0\
set REPO_RELEASE_PATH=%REPO_PATH%release\
set REPO_RELEASE_MOD_PATH=%REPO_RELEASE_PATH%%MODULE_DIR_NAME%\

set TOWERFALL_PATH="C:\Program Files (x86)\Steam\steamapps\common\TowerFall\FortRise\"
set TOWERFALL_MODS_PATH=%TOWERFALL_PATH%Mods\
set TOWERFALL_THIS_MODULE_PATH=%TOWERFALL_MODS_PATH%%MODULE_DIR_NAME%\
set TOWERFALL_THIS_MODULE_AUTO_PATH=%TOWERFALL_MODS_PATH%%BUILD_NAME%\
set TOWERFALL_EXE_PATH=%TOWERFALL_PATH%%EXE_TOWERFALL_NAME%
set EXECUTABLE=%TOWERFALL_PATH%FortRise.exe
set PYRGOS_EXE_PATH="C:\Program Files\Pyrgos\Pyrgos.exe"
